name: qms
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  overlay_support: ^1.0.2
  connectivity: ^0.4.4
  shared_preferences: ^0.5.3+1
  provider: ^4.3.2+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/